# Site settings
title: The Iron Patriots
email: ironpatriots4131@gmail.com
description: > # this means to ignore newlines until "url:"
  The Iron Patriots are FRC Robotics team number 4131 out of Liberty High School in the Issaquah School District.
  We have just finished our fourth competion season and are initiating new members over the summer.
url: "https://endreman0.github.io" # the base hostname & protocol for your site
baseurl: "/FRC4131.github.io" # the subpath of your site, e.g. /blog/
twitter_username: 
github_username: FRC4131
source: _pages

# Build settings
markdown: kramdown
