# Site settings
title: The Iron Patriots
email: lhsfrc4131@gmail.com
description: > # this means to ignore newlines until "url:"
  The Iron Patriots are FRC Robotics team number 4131 out of Liberty High School in the Issaquah School District.
  We have just finished our fourth competion season and are initiating new members over the summer.
url: "https://FRC4131.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: 
github_username: FRC4131
source: _pages
sections:
- text: Home
  url: 
  alts: index
- text: Blog
  url: blog
  alts: 2014;2015;2016
- text: Calendar
  url: calendar
- text: About Us
  url: about
- text: What is FIRST Robotics?
  url: first
- text: Contact Us
  url: contact
- text: Media
  url: media
- text: Sponsors
  url: sponsorship
- text: YouTube
  url: https://www.youtube.com/channel/UC4yU-32WIU4Czi8nTdSphrQ
- text: Github
  url: https://github.com/FRC4131

# Build settings
markdown: kramdown
